name: Java CI/CD with JaCoCo

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  build-test-report:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout source code
        uses: actions/checkout@v4

      - name: ☕ Setup JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: 🔨 Build, Test & Generate JaCoCo Report
        run: mvn clean verify

      - name: 📦 Upload JaCoCo Report as Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: jacoco-report
          path: target/site/jacoco/

      - name: 📦 Zip JaCoCo report
        run: |
          zip -r jacoco-report.zip target/site/jacoco
